name: invalid
description: Package used for input validation.
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
